#!/usr/bin/env python3
"""
Load maze maps for the project.

Supported inputs:
1. Project JSON maps generated by convert_micromouse_maps.py
2. Raw Micromouse ASCII .txt maps
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

try:
    from .convert_micromouse_maps import convert_maze
except ImportError:
    from convert_micromouse_maps import convert_maze


REQUIRED_FIELDS = [
    "maze_id",
    "width",
    "height",
    "wall_matrix",
    "start",
    "goal",
    "goal_cells",
    "risk_cells",
    "narrow_cells",
    "dynamic_updates",
]


def _validate_map_data(data: dict[str, Any], source: Path) -> dict[str, Any]:
    missing = [field for field in REQUIRED_FIELDS if field not in data]
    if missing:
        raise ValueError(f"{source.name}: missing required fields: {missing}")

    width = data["width"]
    height = data["height"]
    wall_matrix = data["wall_matrix"]

    if not isinstance(width, int) or not isinstance(height, int):
        raise ValueError(f"{source.name}: width and height must be integers")

    if len(wall_matrix) != height:
        raise ValueError(f"{source.name}: wall_matrix row count does not match height")

    for row in wall_matrix:
        if len(row) != width:
            raise ValueError(f"{source.name}: wall_matrix column count does not match width")
        for cell in row:
            if not isinstance(cell, list) or len(cell) != 4:
                raise ValueError(
                    f"{source.name}: each wall cell must be [N, E, S, W]"
                )

    return data


def load_map(path: str | Path) -> dict[str, Any]:
    """
    Load a single maze map.

    If path ends with .json, read the converted interface format.
    If path ends with .txt, convert the Micromouse ASCII maze in memory.
    """
    map_path = Path(path)
    if not map_path.exists():
        raise FileNotFoundError(map_path)

    if map_path.suffix.lower() == ".json":
        data = json.loads(map_path.read_text(encoding="utf-8"))
    elif map_path.suffix.lower() == ".txt":
        data = convert_maze(map_path)
    else:
        raise ValueError(f"unsupported map format: {map_path.suffix}")

    return _validate_map_data(data, map_path)


def load_maps(directory: str | Path, suffix: str = ".json") -> list[dict[str, Any]]:
    """
    Load all maps from a directory with the given suffix.
    """
    root = Path(directory)
    if not root.exists():
        raise FileNotFoundError(root)

    maps = [load_map(path) for path in sorted(root.glob(f"*{suffix}"))]
    if not maps:
        raise ValueError(f"no map files with suffix {suffix} found in {root}")
    return maps


def is_goal(map_data: dict[str, Any], x: int, y: int) -> bool:
    """
    Check whether a cell belongs to the goal area.
    """
    return [x, y] in map_data.get("goal_cells", [])


def get_cell_walls(map_data: dict[str, Any], x: int, y: int) -> list[int]:
    """
    Return the wall vector [N, E, S, W] for a given cell.
    """
    return map_data["wall_matrix"][y][x]


def get_neighbors(map_data: dict[str, Any], x: int, y: int) -> list[list[int]]:
    """
    Return all reachable neighboring cells of (x, y).
    """
    width = map_data["width"]
    height = map_data["height"]
    north, east, south, west = get_cell_walls(map_data, x, y)

    neighbors: list[list[int]] = []
    if north == 0 and y - 1 >= 0:
        neighbors.append([x, y - 1])
    if east == 0 and x + 1 < width:
        neighbors.append([x + 1, y])
    if south == 0 and y + 1 < height:
        neighbors.append([x, y + 1])
    if west == 0 and x - 1 >= 0:
        neighbors.append([x - 1, y])

    return neighbors


def summarize_map(map_data: dict[str, Any]) -> dict[str, Any]:
    """
    Return a short summary useful for debugging.
    """
    return {
        "maze_id": map_data["maze_id"],
        "size": [map_data["width"], map_data["height"]],
        "start": map_data["start"],
        "goal": map_data["goal"],
        "goal_cells": map_data["goal_cells"],
        "risk_cells_count": len(map_data["risk_cells"]),
        "narrow_cells_count": len(map_data["narrow_cells"]),
        "dynamic_updates_count": len(map_data["dynamic_updates"]),
    }


if __name__ == "__main__":
    default_map = (
        Path(__file__).resolve().parent.parent
        / "maps"
        / "json"
        / "alljapan-045-2024-exp-fin.json"
    )
    data = load_map(default_map)
    print(json.dumps(summarize_map(data), ensure_ascii=False, indent=2))
